n = int(input("Input width? "))
l = int(input("Input lenght? "))
a = int((n*l)//100)
print(f"The landlord has {a} pieces of land available for sale.")
print(f"He will earn {a*1400} pounds from the sale.")